[package]
name = "luos_driver"
version = "0.1.0"
authors = ["ncros"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
json = "0.12.4"
serial = "0.4.0"